### ISSUE TITLE
[VEST] Homepage - MA Aktualisierung 

### ISSUE THREAD

**Issue by sea1601com** [1601com/vestner-online.de#2]
> Von: Hella Vestner-Lieb [mailto:hella.vestner-lieb@vestner-online.de] 
> Gesendet: Mittwoch, 6. September 2017 16:55
> An: Aydogan Seren | 1601.com <sea@1601.com>
> Betreff: VESTNER// Homepage / Frau Wetekam
> 
> 
> Hallo 1601-Team,
> 
> Wir brauchen bitte Ihre Hilfe:
> 
> Im Bereich Hausverwaltung gibt es eine Mitarbeiterveränderung:
> Herr Rolf Malter ist ausgeschieden (Foto und co. bitte raus)
> 
> Dafür kommt Angela Wetekam  (FOTO separate Mail)
> Immobilienverwalterin
> 
> Für alle gilt die neue Mailadresse: hvw@vestner-online.de  (bitte diese Mailadresse unter jeden Ansprechpartner)
> Durchwahl 20 hat Frau Wetekam
> 
> Könnten Sie bitte die Änderung veranlassen? 
> Foto bitte wieder schwarz/weiß
> 
> Vielen Dank & auf bald
> 
> Hella Vestner-Lieb

https://www.vestner-online.de/de/wir-ueber-uns/das-team-stellt-sich-vor.html

* [x] Kontakt "Rolf Malter" raus
* [x] Neuer Kontakt "Angela Wetekam" stattdessen rein:
Durchwahl: 20
Immobilienverwalterin
Foto bitte wieder schwarz/weiß
* [x] Bitte Bild in Photoshop entkrisseln
![wetekam](https://user-images.githubusercontent.com/12796945/30119128-1359a2d6-9325-11e7-83d9-fc2260d01d53.jpg)
* [x] Bei allen Kontakten bitte künftig einheitlich folgende E-Mail-Addy hinterlegen: `hvw@vestner-online.de`

**Comment by sea1601com** [comment]
![wetekam](https://user-images.githubusercontent.com/12796945/30119128-1359a2d6-9325-11e7-83d9-fc2260d01d53.jpg)

**Comment by sea1601com** [comment]
![image](https://user-images.githubusercontent.com/12796945/30119276-813fc6ea-9325-11e7-87fb-eb0d8f5ea906.png)

- > Bitte Austauschen

**Comment by mt1601com** [comment]
Bild angepasst; aber gibts das in einer größeren Auflösung vll? oder wurde das so zugeschickt?

![vestner_angela_wetekam](https://user-images.githubusercontent.com/12295342/30168322-5d605e6e-93e9-11e7-863c-581848abd0c6.jpg)

**Comment by mt1601com** [comment]
was mir hier aufgefallen ist: Ein Bild tanzt hier aus der Reihe

![bildschirmfoto 2017-09-07 um 16 27 40](https://user-images.githubusercontent.com/12295342/30168370-8079284a-93e9-11e7-9d88-8807d064459e.png)

**Comment by je1601com** [comment]
@mt1601com Das Bild wurde so geschickt, @ADoebeling hat sich gestern schon über die Qualität aufgeregt. ^^' Vielen Dank, dass du es schnell gemacht hast!

Was das Bild angeht, das bunt ist - sieht korrekturwürdig aus, ich erwähne es mal in der Mail an den Kunden wenn ich fertig bin.

**Comment by sea1601com** [comment]
![image](https://user-images.githubusercontent.com/12796945/30170995-f273ac84-93f0-11e7-8bb6-6271e84b680d.png)


Kopfschüttel...

Bitte E-Mail Adresse unter jedem Kontakt hinzufügen:

![image](https://user-images.githubusercontent.com/12796945/30171036-09050a56-93f1-11e7-93bf-3508d9dbb366.png)

**Comment by sea1601com** [comment]
@am1601com Bitte nach Umsetzung von @mt1601com checken und heute der Kundin Bescheid geben. Mit unter gleich nachfragen, was mit dem Farbfoto ist ob wir es ändern sollen.

Danke.

**Comment by ADoebeling** [comment]
![image](https://user-images.githubusercontent.com/10674780/30172179-5b4b222a-93f4-11e7-9887-c76165dc79ed.png)

**Comment by ADoebeling** [comment]
Ich habe hier nochmal drüber gerutscht:

* [x] Anrede Herr/Frau war willkürlich voran gestellt, gefixt
* [x] Abstände zwischen Bild und Text zu groß
* [x] Flucht von Text und Bild teilweise willkürlich
* [x] Teilweise Abstände im Text

Glaube jetzt passt das, @am1601com bitte 4AC und Kontakt
https://www.vestner-online.de/de/wir-ueber-uns/das-team-stellt-sich-vor.html

**Comment by am1601com** [comment]
4AC is doen, Kunde informiert

**Comment by am1601com** [comment]
Doch nur die Hälfte gemacht  :-( 

https://www.vestner-online.de/de/148.html
Auf dieser Seite müssen die Mitarbeiter auch noch ausgetauscht werden.

> From: Hella Vestner-Lieb [mailto:hella.vestner-lieb@vestner-online.de] 
> Sent: Thursday, September 7, 2017 6:55 PM
> To: Support | 1601.com <support@1601.com>
> Subject: Re: AW: VESTNER// Homepage / Frau Wetekam
> 
> Hallo Herr Mürmann,
> 
> Ja - bitte die Ansprechpartner alle in SCHWARZ/WEISS.
> 
> Frau Frömelt ist in Rente- bitte auch löschen.
> 
> WICHTIG: Auf der SEITE HAUSVERWALTUNG MUSS NOCH HERR MALTER RAUS U FRAU WETEKAM REIN- DANKE!
> 
> Mit freundlichen Grüßen 
> Hella Vestner-Lieb
> H. VESTNER GmbH Dienstleistungen
> Erlangen
> Tel. 09131/8853-0
> Fax 09131/207083
> mobil 01712424434
>

**Comment by am1601com** [comment]
* [ ] Hier bist das Foto austauschen
 - https://www.vestner-online.de/de/148.html
![image](https://user-images.githubusercontent.com/30519377/30198340-771536de-946d-11e7-8883-da53db7293f9.png)

* [ ] Hier das Foto auf S/W stylen
 - https://www.vestner-online.de/de/wir-ueber-uns/das-team-stellt-sich-vor.html
![image](https://user-images.githubusercontent.com/30519377/30198392-bf258294-946d-11e7-9be3-a9c299aa486d.png)

* [ ] Und diese Mitarbeiterin bitte auch rausnehmen da nicht mehr im Unternehmen
 - https://www.vestner-online.de/de/wir-ueber-uns/das-team-stellt-sich-vor.html
![image](https://user-images.githubusercontent.com/30519377/30198422-e768aed4-946d-11e7-9d6b-1d04aa5433e9.png)

**Comment by am1601com** [comment]
* [ ] Frau Frömelt soll auf allen Seiten raus!

> Von: Hella Vestner-Lieb [mailto:hella.vestner-lieb@vestner-online.de] 
> Gesendet: Freitag, 8. September 2017 08:42
> An: Support | 1601.com <support@1601.com>
> Betreff: AW: AW: VESTNER// Homepage / Frau Wetekam
> 
> Hallo Mürmann,
> 
> JA -  das muss bitte alles gelöscht werden.
> 
> Frau Frömelt ist im Ruhestand.
> 
> Vielen Dank und auf bald
> 
> Freundliche Grüße
> Hella Vestner-Lieb
> Dipl.-Kffr. (Univ.)
> Geschäftsführerin
> Zeitarbeitsmanager (IHK)
>

**Comment by am1601com** [comment]
@mt1601com habe jetzt alles was ich konnte gemacht.
* [ ] 4AC
* [ ] Farbfoto in S/W wandeln und ersetzen
* [ ] danach info an mich

**Comment by mt1601com** [comment]
![bildschirmfoto 2017-09-08 um 14 04 22](https://user-images.githubusercontent.com/12295342/30210880-b2e1872c-949e-11e7-86ed-c0e8041be1fb.png)

done!

**Comment by am1601com** [comment]
### done

> Von: Mürmann Axel | 1601.com [mailto:am@1601.com] Im Auftrag von Support | 1601.com
> Gesendet: Freitag, 8. September 2017 17:08
> An: 'Hella Vestner-Lieb' <hella.vestner-lieb@vestner-online.de>
> Cc: Support | 1601.com <support@1601.com>
> Betreff: VESTNER// Homepage / Frau Wetekam
> 
> Guten Tag Frau Vestner-Lieb,
> 
> wir sind mit der erweiterten Umsetzung fertig. 
> Folgende Punkte wurden von uns Überarbeitet:
> •	Profilfoto von Fr. Eliza Neufert S/W gefärbt
> •	Austausch von Angela Wetekam auf der Team- und Hausverwaltungsseite
> •	Fr. Frömelt und den Standort Finsterwalde auf allen Seiten (DE/GB/PL) gelöscht
> 
> Zudem haben wir uns um ein paar kleinere Formatierungsauffälligkeiten, die wir in diesem Rahmen gleich mit behoben haben.
> 
> Über eine kurze Rückmeldung von Ihnen zum neuen Stand der Webseite würde ich mich freuen.
> 
> Bei Fragen stehe ich Ihnen gerne zur Verfügung. 
> 
> Viele Grüße und ein schönes Wochenende
> i. A. Axel Mürmann
> Content Management & Support
>
